-- SQL Schema for Persona 5 Portfolio

-- 1. Create Blogs Table
CREATE TABLE IF NOT EXISTS public.blogs (
    id bigint generated by default as identity primary key,
    title text not null,
    date text not null,
    color text default 'bg-red-500',
    description text,
    image_url text,
    is_youtube boolean default false,
    youtube_link text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Messages Table (for the Contact Form)
CREATE TABLE IF NOT EXISTS public.messages (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    message text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Set up Row Level Security (RLS) policies
-- Enable RLS
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read blogs
CREATE POLICY "Allow public read access on blogs" ON public.blogs FOR SELECT USING (true);

-- Allow anyone to insert messages (so the contact form works without login)
CREATE POLICY "Allow public insert on messages" ON public.messages FOR INSERT WITH CHECK (true);

-- 4. Insert a Dummy Blog Post to test
INSERT INTO public.blogs (title, date, color, description, image_url, is_youtube, youtube_link)
VALUES 
('Stealing the First Heart', '14/07/2026', 'bg-red-500', 'Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Nulla porttitor accumsan tincidunt.', null, false, null);

-- 5. Auto-Cleanup Script for Messages (Spam/Storage Protection)
-- Create a function to clean up old messages and keep size in check
CREATE OR REPLACE FUNCTION cleanup_old_messages()
RETURNS void AS $$
BEGIN
  -- 1. Hapus pesan yang usianya lebih dari 1 bulan
  DELETE FROM public.messages WHERE created_at < now() - interval '1 month';
  
  -- 2. Jika ukuran tabel messages masih lebih dari 300MB, 
  --    hapus sisanya dan hanya sisakan 5000 pesan terbaru untuk menghemat tempat.
  IF pg_total_relation_size('public.messages') > 300 * 1024 * 1024 THEN
    DELETE FROM public.messages
    WHERE id NOT IN (
      SELECT id FROM public.messages ORDER BY created_at DESC LIMIT 5000
    );
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Aktifkan ekstensi pg_cron (jika belum aktif)
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Jadwalkan fungsi cleanup untuk berjalan otomatis setiap hari pada jam 00:00 (tengah malam)
-- Dengan berjalan tiap hari, database akan dicek terus agar tidak kepenuhan.
SELECT cron.schedule('cleanup-messages-daily', '0 0 * * *', $$ SELECT cleanup_old_messages(); $$);
