-- SQL Schema for Persona 5 Portfolio

-- 1. Create Blogs Table
CREATE TABLE IF NOT EXISTS public.blogs (
    id bigint generated by default as identity primary key,
    title text not null,
    date text not null,
    color text default 'bg-red-500',
    description text,
    image_url text,
    is_youtube boolean default false,
    youtube_link text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Messages Table (for the Contact Form)
CREATE TABLE IF NOT EXISTS public.messages (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    message text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Set up Row Level Security (RLS) policies
-- Enable RLS
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read blogs
DROP POLICY IF EXISTS "Allow public read access on blogs" ON public.blogs;
CREATE POLICY "Allow public read access on blogs" ON public.blogs FOR SELECT USING (true);

-- Allow anyone to insert messages (so the contact form works without login)
DROP POLICY IF EXISTS "Allow public insert on messages" ON public.messages;
CREATE POLICY "Allow public insert on messages" ON public.messages FOR INSERT WITH CHECK (true);

-- 4. Insert a Dummy Blog Post to test
INSERT INTO public.blogs (title, date, color, description, image_url, is_youtube, youtube_link)
VALUES 
('Stealing the First Heart', '14/07/2026', 'bg-red-500', 'Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Nulla porttitor accumsan tincidunt.', null, false, null);

-- 5. Auto-Cleanup Script for Messages (Spam/Storage Protection)
-- Create a function to clean up old messages and keep size in check
CREATE OR REPLACE FUNCTION cleanup_old_messages()
RETURNS void AS $$
BEGIN
  -- 1. Hapus pesan yang usianya lebih dari 1 bulan
  DELETE FROM public.messages WHERE created_at < now() - interval '1 month';
  
  -- 2. Jika ukuran tabel messages masih lebih dari 300MB, 
  --    hapus sisanya dan hanya sisakan 5000 pesan terbaru untuk menghemat tempat.
  IF pg_total_relation_size('public.messages') > 300 * 1024 * 1024 THEN
    DELETE FROM public.messages
    WHERE id NOT IN (
      SELECT id FROM public.messages ORDER BY created_at DESC LIMIT 5000
    );
  END IF;
END;
$$ LANGUAGE plpgsql;

-- Aktifkan ekstensi pg_cron (jika belum aktif)
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Jadwalkan fungsi cleanup untuk berjalan otomatis setiap hari pada jam 00:00 (tengah malam)
-- Dengan berjalan tiap hari, database akan dicek terus agar tidak kepenuhan.
SELECT cron.schedule('cleanup-messages-daily', '0 0 * * *', $$ SELECT cleanup_old_messages(); $$);

-- ==============================================================================
-- 6. QUERY UNTUK MERESET DAN MERAPIKAN ID (Jalankan sekali saja jika benar-benar perlu)
-- Ganti 'messages' dengan nama tabel kamu yang sebenarnya (misal: 'blogs' atau 'messages')
-- ==============================================================================

-- Memperbarui ID agar berurut (1, 2, 3, dst)
WITH cte AS (
    SELECT id, row_number() OVER (ORDER BY id) as new_id
    FROM messages -- GANTI NAMA TABEL DI SINI
)
UPDATE messages -- GANTI NAMA TABEL DI SINI
SET id = cte.new_id
FROM cte
WHERE messages.id = cte.id;

-- Setelah ID dirapikan, kita harus mengatur ulang sequence auto-incrementnya
-- agar data baru yang masuk tidak bentrok.
SELECT setval(
    pg_get_serial_sequence('messages', 'id'), -- GANTI NAMA TABEL DI SINI
    (SELECT MAX(id) FROM messages)            -- GANTI NAMA TABEL DI SINI
);

/* 
CATATAN PENTING TENTANG DATABASE (PostgreSQL/Supabase):

1. ID yang bolong-bolong (gaps) setelah ada data yang dihapus adalah hal yang SANGAT WAJAR dan NORMAL di database.
2. Sangat TIDAK DISARANKAN membuat sistem otomatis (Trigger) yang mengubah ID secara massal setiap kali ada data yang dihapus. Alasannya:
   - ID berfungsi sebagai identitas unik. Jika ID berubah-ubah, akan merusak relasi dengan tabel lain (Foreign Keys).
   - Memakan performa yang berat jika datanya sudah banyak karena harus mengupdate ribuan baris setiap kali 1 data dihapus.
3. Jika kamu butuh nomor urut untuk ditampilkan di UI (misal: nomor 1, 2, 3 di tabel HTML), lebih baik gunakan index dari array di frontend (React), bukan menggunakan ID dari database.
*/
